description: qn9090 power management configuration for domains

compatible: "sendrato,expanded-power-configs-base-array-test"

properties:

  suspend-to-ram-configs:
    type: string-array
    required: false
    description: Array containing all changeable configurations for the suspend-to-ram state

  gpio-wakeup:
    type: array
    required: false
    description: bool to decide if wakeup source is GPIO

  timer-wakeup:
    type: array
    required: false
    description: bool to decide if wakeup source is timer

  retain-ram-domain: #retain sram
    type: array
    required: false
    description: bool to decide if RAM should be retained between boots

  retain-radio-device: #retain radio
    type: array
    required: false
    description: bool to decide if radio config should be retained between boots


