description: qn9090 power management configuration for domains

compatible: "sendrato,expanded-power-configs-sustoram-substate"

include:
  - name: sendrato,expanded-power-configs-base-substate.yaml
    property-allowlist:
      - gpio-wakeup
      - timer-wakeup
      - retain-ram-domain
      - retain-radio-device

