description: qn9090 power management configuration for domains

compatible: "sendrato,expanded-power-configs-sustoram"

include:
  - name: sendrato,expanded-power-configs-base.yaml
    property-allowlist:
      - gpio-wakeup
      - timer-wakeup
      - retain-ram-domain
      - retain-radio-device

