description: qn9090 power management configuration for domains

compatible: "sendrato,expanded-power-configs-base-substate"

properties:

  gpio-wakeup:
    type: array
    required: false
    description: bool to decide if wakeup source is GPIO

  timer-wakeup:
    type: array
    required: false
    description: bool to decide if wakeup source is timer

  retain-ram-domain:
    type: array
    required: false
    description: bool to decide if RAM should be retained between boots

  retain-radio-device:
    type: array
    required: false
    description: bool to decide if radio config should be retained between boots


